export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_LIST_FETCHING = "PRODUCT_LIST_FETCHING";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";

export const CART_ITEM = "CART_ITEM";
